EW-FH New extension methods for properties with value list items (single/multiselect)
M-Files/VAF.Extensions.Community pull request #12
Opened 2021-02-25 20:23 UTC by falk-huth-ewerk

Background:
There are many helper methods for handling references to object types but to less for handling value lists and their items - especially in connection with those which where synchronised from external data sources - to have the same IDs on multiple vaults and other systems.

Rudimentary tests are already available but should be reviewed, Perhaps there are other ways to reach the goal more easily.

2021-02-26 10:16 UTC, falk-huth-ewerk commented
@CraigHawker  Here again.

2021-02-26 10:48 UTC, CraigHawker commented on MFiles.VAF.Extensions/ExtensionMethods/ObjVerEx/GetPropertyAsValueListItems.cs
> +                    vliOps.GetValueListItemByID(propDef.ValueList, lookup.Item)
Have you tested what happens if the value list item has been deleted/destroyed?  Does it return null as the method XML states, or does it throw an exception?

2021-02-26 10:55 UTC, CraigHawker commented on MFiles.VAF.Extensions.Tests/ExtensionMethods/ObjVerEx/GetPropertyAsValueListItems.cs
> +            ((Common.ObjVerEx) null).GetPropertyAsValueListItems((int) -1);
This test does not pass.  The exception throws an ArgumentNullException - did you mean to use a valid ObjVerEx instance?

2021-02-26 10:55 UTC, CraigHawker commented on MFiles.VAF.Extensions.Tests/ExtensionMethods/ObjVerEx/GetPropertyAsValueListItems.cs
> +            ((Common.ObjVerEx) null).GetPropertyAsValueListItems(int.MaxValue);
This test does not pass.  The exception throws an ArgumentNullException - did you mean to use a valid ObjVerEx instance?

2021-02-26 10:56 UTC, CraigHawker commented on MFiles.VAF.Extensions.Tests/ExtensionMethods/ObjVerEx/GetPropertyAsValueListItems.cs
> +            ((Common.ObjVerEx) null).GetPropertyAsValueListItems((int) MFBuiltInPropertyDef.MFBuiltInPropertyDefDeleted);
This test does not pass.  The exception throws an ArgumentNullException - did you mean to use a valid ObjVerEx instance?

2021-02-26 10:56 UTC, CraigHawker commented on MFiles.VAF.Extensions.Tests/ExtensionMethods/ObjVerEx/GetPropertyAsValueListItems.cs
> +            ((Common.ObjVerEx) null).GetPropertyAsValueListItems((int) MFBuiltInPropertyDef.MFBuiltInPropertyDefWorkflow);
This test does not pass.  The exception throws an ArgumentNullException - did you mean to use a valid ObjVerEx instance?

2021-02-26 10:58 UTC, CraigHawker commented on MFiles.VAF.Extensions.Tests/ExtensionMethods/ObjVerEx/GetPropertyAsValueListItems.cs
> +        // TODO Think about further test methods + Question how lookups to object types were handled
Some additional tests are needed here (could be done after merge, but must be done before release) to test valid scenarios (e.g. a valid property value type).

See examples on `GetPropertyAsSimpleTypeBase<T>` on how to mock the required structures.

2021-02-26 11:01 UTC, CraigHawker commented on MFiles.VAF.Extensions.Tests/ExtensionMethods/ObjVerEx/GetPropertyAsValueListItem.cs
> +            ((Common.ObjVerEx) null).GetPropertyAsValueListItem((int) -1);
This test does not pass.  The exception throws an ArgumentNullException - did you mean to use a valid ObjVerEx instance?

2021-02-26 11:01 UTC, CraigHawker commented on MFiles.VAF.Extensions.Tests/ExtensionMethods/ObjVerEx/GetPropertyAsValueListItem.cs
> +            ((Common.ObjVerEx) null).GetPropertyAsValueListItem(int.MaxValue);
This test does not pass.  The exception throws an ArgumentNullException - did you mean to use a valid ObjVerEx instance?

2021-02-26 11:01 UTC, CraigHawker commented on MFiles.VAF.Extensions.Tests/ExtensionMethods/ObjVerEx/GetPropertyAsValueListItem.cs
> +            ((Common.ObjVerEx) null).GetPropertyAsValueListItem((int)MFBuiltInPropertyDef.MFBuiltInPropertyDefDeleted);
This test does not pass.  The exception throws an ArgumentNullException - did you mean to use a valid ObjVerEx instance?

2021-02-26 11:02 UTC, CraigHawker commented on MFiles.VAF.Extensions.Tests/ExtensionMethods/ObjVerEx/GetPropertyAsValueListItem.cs
> +        // TODO Think about further test methods + Question how lookups to object types were handled
Some additional tests are needed here (could be done after merge, but must be done before release) to test valid scenarios (e.g. a valid property value type).

See examples on GetPropertyAsSimpleTypeBase<T> on how to mock the required structures.

2021-02-26 11:04 UTC, CraigHawker requested changes
I have added some comments to the current submission.  In general I think these are very good methods to add, but at a minimum the tests need to pass before merge.

There should also be some tests to ensure that this executes correctly, not just testing error conditions.  I am happy to help with these once the above tests are resolved.

2021-02-27 21:38 UTC, falk-huth-ewerk commented
@CraigHawker Tests run now correctly

Further tests are not possible as easy as you may think. vault.PropertyDefOperations returns empty PropertyDef set and you cannot add PropertyDef for testing. You can call AddPropertyDefAdmin but the new value doesn't get persisted because no real vault is connected. You have to implement a complete Vault mock for that.

2021-03-01 08:32 UTC, CraigHawker commented
I have marked as resolved the comments related to the existing tests.  I have also done a merge from the primary branch as there was a conflict there.

2021-03-01 10:20 UTC, CraigHawker commented on MFiles.VAF.Extensions.Tests/ExtensionMethods/ObjVerEx/GetPropertyAsValueListItem.cs
> +        // TODO Think about further test methods + Question how lookups to object types were handled
Example unit tests included in commit 29f556895f81fb2232e1d7be75f406ee0f95f35a.

2021-03-02 09:34 UTC, CraigHawker commented on MFiles.VAF.Extensions.Tests/ExtensionMethods/ObjVerEx/GetPropertyAsValueListItems.cs
> +        // TODO Think about further test methods + Question how lookups to object types were handled
Commit d60f7e500c76c15a7eda71cbbd77ecf2ef7b78a0 includes examples of unit tests for `GetPropertyAsValueListItems`.

2021-03-02 09:35 UTC, CraigHawker commented
Unit tests added and green.  Will merge later today.

2021-03-02 09:37 UTC, CraigHawker commented on MFiles.VAF.Extensions/ExtensionMethods/ObjVerEx/GetPropertyAsValueListItems.cs
> +                    vliOps.GetValueListItemByID(propDef.ValueList, lookup.Item)
Items that are deleted are returned (provided the user has sufficient privileges, which is the case for VAF code), but have their "Deleted" property set to true.
Items that are not found throw an exception, not return null.  Commit 0de244ade1cc07d1ecd6f4299303612b0b130174 deals with this and alters the XML to describe the behaviour.

2021-03-02 09:37 UTC, merged