Fix for #132
M-Files/VAF.Extensions.Community pull request #133
Opened 2024-06-13 14:51 UTC by MirkoSc

Thats the PR for Issue #132

2024-06-14 07:39 UTC, CraigHawker requested changes
Looks good.  Can you just make that small change please and I will merge and publish.

2024-06-14 07:39 UTC, CraigHawker commented on MFiles.VAF.Extensions/Dashboards/ApplicationOverviewDashboardContent/DefaultApplicationOverviewDashboardContentRenderer.cs
> +					this.VaultApplication?.License ?? null,
The ?? null is redundant

2024-06-14 11:02 UTC, MirkoSc commented on MFiles.VAF.Extensions/Dashboards/ApplicationOverviewDashboardContent/DefaultApplicationOverviewDashboardContentRenderer.cs
> +					this.VaultApplication?.License ?? null,
Oh yes thats right. I fixed it now.

2024-06-17 10:31 UTC, CraigHawker approved these changes

2024-06-17 10:31 UTC, merged